creating imazon shp data function
datazoompuc/datazoom.amazonia pull request #106
Opened 2022-06-21 03:53 UTC by luizguilhermelopesm

-creating function to download imazon's shapfile dataset 
-intially, the function is for internal use

2022-07-26 20:06 UTC, FranciscoCavalcanti requested changes
@luizguilhermelopesm 

Infelizmente não consegui fazer o download na função `load_imazon`. Reproduzo abaixo o output no meu console.

Ademais, é preciso alterar alguns documentos como NEWS.md e README.md para anunciar a atualização.

```
imazon <- load_imazon(dataset = "imazon_shp")
Please follow the steps from `googledrive` package to download the data. This may take a while.
Error in `gargle_abort_request_failed()`:
! Client error: (403) Forbidden
Insufficient Permission: Request had insufficient authentication scopes.
* domain: global
* reason: insufficientPermissions
* message: Insufficient Permission: Request had insufficient authentication scopes.
Run `rlang::last_error()` to see where the error occurred.

```

2022-08-09 18:50 UTC, FranciscoCavalcanti requested changes
@luizguilhermelopesm  Tentei rodar a função `load_imazon` sem sucesso. Segue abaixo o resultado no console do RStudio para averiguação.

```
> library(devtools)
Carregando pacotes exigidos: usethis
Warning messages:
1: package ‘devtools’ was built under R version 4.1.3 
2: package ‘usethis’ was built under R version 4.1.3 
> devtools::install()
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                  
2: CRAN packages only                   
3: None                                 
4: rlang   (1.0.2    -> 1.0.4   ) [CRAN]
5: stringi (1.7.6    -> 1.7.8   ) [CRAN]
6: tibble  (3.1.7    -> 3.1.8   ) [CRAN]
7: RCurl   (1.98-1.7 -> 1.98-1.8) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
v  checking for file 'C:\Users\f.cavalcanti\Documents\GitHub\datazoom.amazonia/DESCRIPTION'
-  preparing 'datazoom.amazonia': (26.1s)
v  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1.4s)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'datazoom.amazonia_0.7.2.9000.tar.gz'
   
Running "C:/PROGRA~1/R/R-41~1.0/bin/x64/Rcmd.exe" INSTALL "C:\Users\FEB8D~1.CAV\AppData\Local\Temp\RtmpiYm0Sk/datazoom.amazonia_0.7.2.9000.tar.gz" \
  --install-tests 
* installing to library 'C:/Users/f.cavalcanti/Documents/R/win-library/4.1'
* installing *source* package 'datazoom.amazonia' ...
** using staged installation
** libs
"C:/RBuildTools/4.0/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG  -I'C:/Users/f.cavalcanti/Documents/R/win-library/4.1/Rcpp/include'        -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c blast.c -o blast.o
"C:/RBuildTools/4.0/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG  -I'C:/Users/f.cavalcanti/Documents/R/win-library/4.1/Rcpp/include'        -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c datazoom.amazonia_init.c -o datazoom.amazonia_init.o
"C:/RBuildTools/4.0/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG  -I'C:/Users/f.cavalcanti/Documents/R/win-library/4.1/Rcpp/include'        -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c dbc2dbf.c -o dbc2dbf.o
C:/RBuildTools/4.0/mingw64/bin/gcc -shared -s -static-libgcc -o datazoom.amazonia.dll tmp.def blast.o datazoom.amazonia_init.o dbc2dbf.o -LC:/PROGRA~1/R/R-41~1.0/bin/x64 -lR
installing to C:/Users/f.cavalcanti/Documents/R/win-library/4.1/00LOCK-datazoom.amazonia/00new/datazoom.amazonia/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'datazoom.amazonia'
    finding HTML links ... done
    dbc2dbf                                 html  
    load_baci                               html  
    load_br_trade                           html  
    load_cempre                             html  
    load_cipo                               html  
    load_climate                            html  
    load_datasus                            html  
    load_degrad                             html  
    load_deter                              html  
    load_ibama                              html  
    load_iema                               html  
    load_imazon                             html  
    load_ips                                html  
    load_mapbiomas                          html  
    load_pam                                html  
    load_pevs                               html  
    load_pibmunic                           html  
    load_ppm                                html  
    load_prodes                             html  
    load_seeg                               html  
    load_sigmine                            html  
    read.dbc                                html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (datazoom.amazonia)
> ?datazoom.amazonia::load_imazon()
> imazon <- load_imazon(dataset = "imazon_shp")
Error in load_imazon(dataset = "imazon_shp") : 
  não foi possível encontrar a função "load_imazon"
> imazon <- datazoom.amazonia::load_imazon(dataset = "imazon_shp")
Please follow the steps from `googledrive` package to download the data. This may take a while.
The googledrive package is requesting access to your Google account.
Select a pre-authorised account or enter '0' to obtain a new token.
Press Esc/Ctrl + C to cancel.

1: francisco.lima.cavalcanti@gmail.com

Selection: 1
Auto-refreshing stale OAuth token.
Error in `gargle_abort_request_failed()`:
! Client error: (403) Forbidden
Insufficient Permission: Request had insufficient authentication scopes.
* domain: global
* reason: insufficientPermissions
* message: Insufficient Permission: Request had insufficient authentication scopes.
Run `rlang::last_error()` to see where the error occurred.
```

2022-08-09 22:13 UTC, luizguilhermelopesm commented
@FranciscoCavalcanti acho que entendi o problema! os meus testes estavam dando certo, porque estava utilizando na autenticação do R meu @gmail que tem a permissão de acesso no drive do datazoom. Para qualquer email funcionar acho que temos que ter o nosso drive como público.
Fiz um teste com outro email e deu a mesma coisa que no seu.

2022-08-24 17:19 UTC, FranciscoCavalcanti approved these changes

2022-08-24 17:20 UTC, merged