Deter
datazoompuc/datazoom.amazonia pull request #14
Opened 2021-01-20 20:05 UTC by IgorRigolon

2021-01-21 16:29 UTC, victordamatta reviewed
Muito bom! Alguns pontos:
- O check() dá duas NOTEs que é melhor tirar. 
- Seria bom adaptar o código ao tidyverse styleguide: https://style.tidyverse.org/. Só rodar uma ferramenta que automatiza isso. 
- Acho que vale ter também o código dos municípios do IBGE pra ajudar a mergear as bases de dados.
- eu não entendi que unidade está sendo usada para medir área. Isso entra na documentação e talvez como um tipo no R mesmo.
- Faltou criar um vignette! Dá uma olhada no livro R packages e nas outras do nosso pacote. Principal coisa a ter na vignette do DETER provavelmente é alguma descrição do dataset.

2021-01-21 16:29 UTC, victordamatta commented on R/deter.R
> +    df <- read.dbf(utils::unzip(temp, "deter_public.dbf"), as.is = TRUE) %>%
Melhor fazer o `unzip` dentro da pasta temporária. Isso conserta um dos NOTEs que eu mencionei

2021-01-21 16:29 UTC, victordamatta commented on R/deter.R
> +  else {df = warning("Invalid source.")}
Esse padrão não é bom. Melhor jogar um erro se a source é inválida.

2021-01-21 16:29 UTC, victordamatta commented on R/deter.R
> +  if (aggregation_level == "state") {
Melhor conectar esses `if`s com `else if`s e afins

2021-01-21 16:29 UTC, victordamatta commented on R/deter.R
> +    dplyr::select(-c(QUADRANT, PATH_ROW, SENSOR, SATELLITE)) %>%
Pra consertar a outra NOTE você vai precisar inserir uma porrada de `.data$` nessa seção do código

2021-01-21 16:29 UTC, victordamatta commented on R/deter.R
> +#' load_deter("C:\\...\\'deter'.zip", aggregation_level = "municipality")
Esse exemplo não é muito bom porque está adaptado ao seu computador. Acredito que ele só não falha porque pela sua lógica quando o código não consegue funcionar ele dá um warning e encerra (o que não é bom, veja outros comentários abaixo). É legal colocar um exemplo com file path, aí tem dois caminhos. Ou faz do jeito que eu fiz no prodes com `system.file`, que hoje em dia eu acho too much. Ou simplesmente coloca um `\dontrun{}` em volta, mas aí põe um path mais simbólico e expressivo.

2021-01-21 16:29 UTC, victordamatta commented on R/deter.R
> +load_deter = function(source, aggregation_level = "municipality",  language = "eng") {
Acho que nesse caso vale colocar `source = "amazonia"` porque esperamos que a maioria dos usuários queiram isso.

2021-01-21 16:52 UTC, IgorRigolon commented on R/deter.R
> +  if(!is.character(df)){
Isso foi um pra tirar erro que tava dando por causa daquilo que eu tinha feito com o `else{df <- warning("...")}`. Quando a source era inválida, o df virava character aí dava erro quando passava pelo select e afins. Mas é bastante barbeiragem mesmo, vou arrumar essas coisas.

2021-01-28 23:17 UTC, FranciscoCavalcanti requested changes
Oi @IgorRigolon, 

O branch está quase 100%, falta apenas alguns ajustes que listo abaixo:

1. É preciso alterar o documento README.md para incorporar as mudanças que essa sua branch vai trazer para o pacote datazoom.amazonia. Especificamente na linha 4, para informar que agora temos dados do INPE Deter. E especificamente entre as linhas 26-33 para mostrar um exemplo da nova função.
2. É preciso alterar o documento NEWS.md para incorporar a noticia da nova versão. Especificamente, após a linha 13. Você deve alterar também a numeração da versão e em seguida alterar essa informação no DESCRIPTION.

2021-01-28 23:17 UTC, FranciscoCavalcanti commented on DESCRIPTION
>      sidrar,
@IgorRigolon no documento DESCRIPTION é preciso fazer mais algumas alterações. 

1. Você precisa se inserir como novo autor (na linha 10).  
2. Você precisa alterar a versão do datazoom.amazonia (linha 3)

2021-02-03 22:38 UTC, FranciscoCavalcanti approved these changes

2021-02-03 22:51 UTC, FranciscoCavalcanti approved these changes
@IgorRigolon codigo passou em todos testes do Github Action, e passou também no `devtools::check()`.

Além disso rodei:


```
data <- load_deter(
  source = "amazonia",
  space_aggregation = "municipality",
  time_aggregation = "year",
  language = "pt"
)

```

E consegui resultados satisfatórios entre 2016 e 2021.

2021-02-03 22:57 UTC, merged