Ibama agoravai
datazoompuc/datazoom.amazonia pull request #16
Opened 2021-01-22 18:25 UTC by arthurcbps

vamos ver se agora vai. Perdão pela confusão

2021-01-22 21:33 UTC, FranciscoCavalcanti requested changes
@arthurcbps 

O código não conseguiu concluir um `devtools::check()` no meu console. Percebe-se que o código precisa ser revisado inclusive pois não passou em nenhum dos 5 testes no Github Action.

2021-01-22 21:33 UTC, FranciscoCavalcanti commented on NEWS.md
> +* Added functions for COMEX data
Falta incluir aqui no NEWS.md da incorporação dos dados do ibama

2021-01-22 21:33 UTC, FranciscoCavalcanti commented on .gitignore
> +R/fines_ibama.R
A inclucão do `fines_ibama.R` no .gitignore não é necessária.

2021-01-22 21:33 UTC, FranciscoCavalcanti commented on DESCRIPTION
> +    )
Necessário incluir @arthurcbps como autor do pacote.

2021-01-22 21:33 UTC, FranciscoCavalcanti commented on DESCRIPTION
> +    XML
Houve uma mudança brusca aqui no qual não estou seguro que esteja correto. Em particular, foram deletados vários librabries, como por exemplo `sidrar`, no qual é necessário para baixar os dados do PIB per capita. 

É preciso revisar esse documento.

2021-01-22 21:33 UTC, FranciscoCavalcanti commented on NAMESPACE
> +importFrom(rlang,.data)
Aqui é um claro indicativo de que o pacote não está atualizado com todas funcionalidades pois `load_comex`, `load_gdp`, etc, foram deletados.

É preciso revisar o código com um `devtools::document()`.

2021-01-22 21:33 UTC, FranciscoCavalcanti commented on R/fines_ibama.R
> +fines_ibama <- function(download_data = TRUE,
eu gostaria que o nome do arquivo mudasse de **fines_ibama.R** para **ibama.R**.

Já com relação a função na linha 59, eu gostaria que nome mudasse de `fines_ibama` para `ibama_fines`. Isso porque a medida que inserimos novas funionalidades ao **ibama.R** bastaria usar o nome da funcionalidade depois do nome ibama. Por exemplo, `ibama_value`, `ibama_motive`, `ibama_expenditure`, etc.

2021-01-22 21:51 UTC, arthurcbps commented on DESCRIPTION
> +    )
eu posso retirar a Maria?

2021-01-23 13:14 UTC, FranciscoCavalcanti commented on DESCRIPTION
> +    )
Na verdade não. Maria participou da construção desse pacote. A idéia é colocar todas as pessoas que contribuiram ao longo da história.

2021-01-23 13:20 UTC, FranciscoCavalcanti requested changes
@arthurcbps, pensando melhor, acho que o nome da função deveria ser `load_ibama`, pois este é o padrão em todas as outras bases de dados (`load_prodes`, `load_comex`, `load_mapbiomas`, etc).

2021-01-28 22:51 UTC, FranciscoCavalcanti requested changes
Oi @arthurcbps

Eu falhei em instalar ( `devtools::install()` ) o pacote `datazoom.amazonia` na atual versão dessa branch . Tentei instalar de três formas. 

1. Primeiro, por cima da versão master do pacote `datazoom.amazonia`
2. Após remover o pacote e e em seguida tentar instalar.
3. Em seguida, tentei checar a instalação nas outras branch (funcionou bem), e por fim tentei mais umvez instalar sem sucesso.

Abaixo copio o resultado no console.

Em vista que branch também não passou em nenhum dos 5 testes do Gitbub Action, acredito que olhar a documentação de cada teste pode lhe ajudar a entender o que deve ser consertado.

Resultado no console após rodar  `devtools::install()` :

```
√  checking for file 'C:\Users\Francisco\Dropbox\DataZoom\datazoom.amazonia/DESCRIPTION' (638ms)
-  preparing 'datazoom.amazonia': (2.1s)
E  checking DESCRIPTION meta-information ... 
   Malformed Depends or Suggests or Imports or Enhances field.
   Offending entries:
     readxl
   XML
   Entries must be names of packages optionally followed by '<=' or '>=',
   white space, and a valid version number in parentheses.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Malformed Depends or Suggests or Imports or Enhances field.
E> Offending entries:
E>   readxl
E> XML
E> Entries must be names of packages optionally followed by '<=' or '>=',
E> white space, and a valid version number in parentheses.
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
E> 
Type .Last.error.trace to see where the error occured
> devtools::check()
Updating datazoom.amazonia documentation
Loading datazoom.amazonia
Invalid DESCRIPTION:
Malformed Depends or Suggests or Imports or Enhances field.
Offending entries:
  readxl
XML
Entries must be names of packages optionally followed by '<=' or '>=', white
space, and a valid version number in parentheses.

See section 'The DESCRIPTION file' in the 'Writing R Extensions' manual.

Warning in (function (dep_name, dep_ver = "*")  :
  Dependency package 'readxl
    XML' not available.
Erro: Dependency package(s) 'readxl
    XML' not available.
Run `rlang::last_error()` to see where the error occurred.

```

2021-01-28 22:51 UTC, FranciscoCavalcanti commented on README.md
> +* MAPBIOMAS: land covering by municipality or state
É preciso inserir informação que o datazoom.amazonia comporta dados do IBAMA aqui

2021-01-28 22:51 UTC, FranciscoCavalcanti commented on README.md
> +```
Também inserir um exemplo da função para Ibama

2021-01-29 18:00 UTC, arthurcbps commented on R/ibama.R
> +fines_data_agg <- function(dataset, t = c("year", "month"), g = "city",
Mudei o nome para `aggregate_ibama.` Não sei é o quão generalizável é essa função para outros casos, dado que ela faz algumas coisas que são específicas ao caso do IBAMA, como dizer o número de cpfs/cnpjs responsáveis pelas infrações em cada lugar.

2021-01-29 19:08 UTC, arthurcbps commented
Por algum motivo os checks falham na hora de gerar a vignette do PRODES

2021-02-18 15:40 UTC, FranciscoCavalcanti requested changes
@arthurcbps segue abaixo os comentários para a revisão do código.

1. Neste código você fez alterações nas vignettes de todas as funções para elas não rodarem no **Github Action**. No entanto, ficamos acordados de que está tudo bem os `checks` não passerem pelos exemplos, mas eles devem sim passar pelas vignettes. Por isso, voce deveria refazer as alterações nas vignettes. Ademais, acho que essa tarefa deveria ser feita por outro branch. 
2. Quando rodei o `devtools::check()`, na primeira vez deu `1 error, 1 warning, 1 note`. (duracao 22 min). O `error` se referia ao site do INPE que havia caido. Em seguida rodei mais uma vez e deu `0 error, 1 warning, 1 note` (18 min). O warning é o velho conhecido qpdf e o note eu copio abaixo. Tentar uma olhada nesse potencial problema. Aperentemente, tem haver com o fortmato do aquivo baixado. Talvez uma outra funcao para baixar os dados nesse formato resolva:
```

> checking for non-standard things in the check directory ... NOTE
  Found the following files/directories:
    'fines.rar' 'rel_areas_embargadas_0-65000_2021-02-18_080019.xls'

```    
3. Tentei baixar os dados com a função anotada no vignette mas deu erro. Copio o resultado abaixo.

```
> load_ibama(
+   download_data = TRUE, 
+   download_directory = 'C:/Users/Francisco/Desktop/',
+   time_aggregation = c('month', 'year'),
+   space_aggregation = c('municipality', 'state'),
+   years = c(2010, 2012),
+   language = "eng"
+ )
tentando a URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/downloadListaAreasEmbargadas.php'
Content type 'application/zip' length 6758789 bytes (6.4 MB)
downloaded 6.4 MB

Error in h(simpleError(msg, call)) : 
  erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites'
Além disso: Warning message:
 Error in h(simpleError(msg, call)) : 
  erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites' 
>

```

Tenta resolver esses problemas, e em seguida me marca denovo com reviewer.

2021-02-18 18:19 UTC, arthurcbps commented
> @arthurcbps segue abaixo os comentários para a revisão do código.
> 
> 1. Neste código você fez alterações nas vignettes de todas as funções para elas não rodarem no **Github Action**. No entanto, ficamos acordados de que está tudo bem os `checks` não passerem pelos exemplos, mas eles devem sim passar pelas vignettes. Por isso, voce deveria refazer as alterações nas vignettes. Ademais, acho que essa tarefa deveria ser feita por outro branch.
> 2. Quando rodei o `devtools::check()`, na primeira vez deu `1 error, 1 warning, 1 note`. (duracao 22 min). O `error` se referia ao site do INPE que havia caido. Em seguida rodei mais uma vez e deu `0 error, 1 warning, 1 note` (18 min). O warning é o velho conhecido qpdf e o note eu copio abaixo. Tentar uma olhada nesse potencial problema. Aperentemente, tem haver com o fortmato do aquivo baixado. Talvez uma outra funcao para baixar os dados nesse formato resolva:
> 
> ```
> 
> > checking for non-standard things in the check directory ... NOTE
>   Found the following files/directories:
>     'fines.rar' 'rel_areas_embargadas_0-65000_2021-02-18_080019.xls'
> ```
> 
> 1. Tentei baixar os dados com a função anotada no vignette mas deu erro. Copio o resultado abaixo.
> 
> ```
> > load_ibama(
> +   download_data = TRUE, 
> +   download_directory = 'C:/Users/Francisco/Desktop/',
> +   time_aggregation = c('month', 'year'),
> +   space_aggregation = c('municipality', 'state'),
> +   years = c(2010, 2012),
> +   language = "eng"
> + )
> tentando a URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/downloadListaAreasEmbargadas.php'
> Content type 'application/zip' length 6758789 bytes (6.4 MB)
> downloaded 6.4 MB
> 
> Error in h(simpleError(msg, call)) : 
>   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites'
> Além disso: Warning message:
>  Error in h(simpleError(msg, call)) : 
>   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites' 
> >
> ```
> 
> Tenta resolver esses problemas, e em seguida me marca denovo com reviewer.
 Francisco, sobre esse 'NOTE', é aquela coisa de, quando os dados são baixados ao rodar o exemplo, eles são armazenados na pasta onde está o pacote. Coloquei o \dontrun, de forma que deve resolver.
 
 Quanto ao erro que deu, eu consertei uma coisa no código e rodei aqui. Deu tudo certo no meu caso

2021-02-19 16:49 UTC, FranciscoCavalcanti reviewed
@arthurcbps, observe que nesse _commit_ você fez upload dos arquivos **fines.rar** e  **vignettes/rel_areas_embargadas_0-65000_2021-02-18_080019.xls**. É preciso deleta-los.

2021-02-19 20:04 UTC, arthurcbps commented
> @arthurcbps, observe que nesse _commit_ você fez upload dos arquivos **fines.rar** e **vignettes/rel_areas_embargadas_0-65000_2021-02-18_080019.xls**. É preciso deleta-los.

resolvido!

2021-02-23 13:04 UTC, FranciscoCavalcanti reviewed
@arthurcbps  apenas atualizando o resultado no meu console após rodar o vignette para o Ibama:

```
> load_ibama(
+   download_data = TRUE, 
+   download_directory = 'C:/Users/Francisco/Desktop/',
+   time_aggregation = c('month', 'year'),
+   space_aggregation = c('municipality', 'state'),
+   years = c(2010, 2012),
+   language = "eng"
+ )
tentando a URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/downloadListaAreasEmbargadas.php'
Content type 'application/zip' length 6758510 bytes (6.4 MB)
downloaded 6.4 MB

Error in h(simpleError(msg, call)) : 
  erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites'
Além disso: Warning message:
 Error in h(simpleError(msg, call)) : 
  erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites' 
>

```

2021-02-23 16:03 UTC, arthurcbps commented
> @arthurcbps apenas atualizando o resultado no meu console após rodar o vignette para o Ibama:
> 
> ```
> > load_ibama(
> +   download_data = TRUE, 
> +   download_directory = 'C:/Users/Francisco/Desktop/',
> +   time_aggregation = c('month', 'year'),
> +   space_aggregation = c('municipality', 'state'),
> +   years = c(2010, 2012),
> +   language = "eng"
> + )
> tentando a URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/downloadListaAreasEmbargadas.php'
> Content type 'application/zip' length 6758510 bytes (6.4 MB)
> downloaded 6.4 MB
> 
> Error in h(simpleError(msg, call)) : 
>   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites'
> Além disso: Warning message:
>  Error in h(simpleError(msg, call)) : 
>   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites' 
> >
> ```

@FranciscoCavalcanti engraçado, comigo funcionou... seja colocando meu desktop noo argumento download_directory, ou colocando getwd(). Realmente não sei explicar... Você chegou a atualizar no seu desktop com os erros que consertei?

2021-02-23 16:42 UTC, FranciscoCavalcanti commented
> > @arthurcbps apenas atualizando o resultado no meu console após rodar o vignette para o Ibama:
> > ```
> > > load_ibama(
> > +   download_data = TRUE, 
> > +   download_directory = 'C:/Users/Francisco/Desktop/',
> > +   time_aggregation = c('month', 'year'),
> > +   space_aggregation = c('municipality', 'state'),
> > +   years = c(2010, 2012),
> > +   language = "eng"
> > + )
> > tentando a URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/downloadListaAreasEmbargadas.php'
> > Content type 'application/zip' length 6758510 bytes (6.4 MB)
> > downloaded 6.4 MB
> > 
> > Error in h(simpleError(msg, call)) : 
> >   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites'
> > Além disso: Warning message:
> >  Error in h(simpleError(msg, call)) : 
> >   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites' 
> > >
> > ```
> 
> @FranciscoCavalcanti engraçado, comigo funcionou... seja colocando meu desktop noo argumento download_directory, ou colocando getwd(). Realmente não sei explicar... Você chegou a atualizar no seu desktop com os erros que consertei?

@arthurcbps,

2021-02-23 16:45 UTC, FranciscoCavalcanti commented
> > @arthurcbps apenas atualizando o resultado no meu console após rodar o vignette para o Ibama:
> > ```
> > > load_ibama(
> > +   download_data = TRUE, 
> > +   download_directory = 'C:/Users/Francisco/Desktop/',
> > +   time_aggregation = c('month', 'year'),
> > +   space_aggregation = c('municipality', 'state'),
> > +   years = c(2010, 2012),
> > +   language = "eng"
> > + )
> > tentando a URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/downloadListaAreasEmbargadas.php'
> > Content type 'application/zip' length 6758510 bytes (6.4 MB)
> > downloaded 6.4 MB
> > 
> > Error in h(simpleError(msg, call)) : 
> >   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites'
> > Além disso: Warning message:
> >  Error in h(simpleError(msg, call)) : 
> >   erro na avaliação do argumento 'doc' na seleção do método para a função 'readHTMLTable': 'índice fora de limites' 
> > >
> > ```
> 
> @FranciscoCavalcanti engraçado, comigo funcionou... seja colocando meu desktop noo argumento download_directory, ou colocando getwd(). Realmente não sei explicar... Você chegou a atualizar no seu desktop com os erros que consertei?

@arthurcbps, a última versão do branch ibama_agoravai foi a 3 dias atrás, no commit intitulado "delete downloaded files". O rodei mais uma vez o comnado, e o resultado permanece igual.

2021-04-27 17:10 UTC, dacbarbosa approved these changes

2021-04-27 17:10 UTC, merged