Created IPS function
datazoompuc/datazoom.amazonia pull request #17
Opened 2021-01-27 00:51 UTC by arthurcbps

2021-01-28 22:58 UTC, FranciscoCavalcanti requested changes
@arthurcbps 

Este Pull Request, possui documentos conflituosos com o branch `master `atual. É preciso resolver incorporando as última atualizações do `master` neste branch.

2021-01-28 22:58 UTC, FranciscoCavalcanti commented on NEWS.md
> +* Added functions for IPS data
Aqui deve estar confliuoso com o branch `master`. É preciso atualizar este branch com a versão mais recente do branch `master`.

2021-01-28 22:58 UTC, FranciscoCavalcanti commented on R/IPS.R
> +load_IPS_data <- function(download_directory, language = 'english'){
renomear para `load_ips`

2021-02-18 17:54 UTC, FranciscoCavalcanti requested changes
@arthurcbps, o código rodou bem e consegui baixar os dados do IPS de forma satisfatória. No entanto para aceitar esse branch, eu gosataria que você refizesse as alterações nas vignettes. Isso porque ficamos acordados de que está tudo bem os `checks` do **Github Action** não passerem pelos exemplos, mas eles devem sim passar pelas vignettes.

2021-02-22 21:40 UTC, FranciscoCavalcanti requested changes
@arthurcbps, o devtools::check falhou. Aparentemente é um erro do vignette do IPS.Rmd. Colo abaixo o resultado no console.

Uma dúvida: vi que você alterou em todos os vignettes o comando `{r, include = FALSE}`  para `{r setup, include = FALSE}`. Você está ativando os vignettes com esse comando? Não me parece isso. Lembrando que o que eu pedi foi ativar os vignettes e nos exemplos colocar o \dontrun{}. Assim como você fez prodes.R

```
> devtools::check()
Updating datazoom.amazonia documentation
Loading datazoom.amazonia
Writing NAMESPACE
Writing NAMESPACE
-- Building --------------------------------------------------- datazoom.amazonia --
Setting env vars:
* CFLAGS    : -Wall -pedantic
* CXXFLAGS  : -Wall -pedantic
* CXX11FLAGS: -Wall -pedantic
------------------------------------------------------------------------------------
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\Francisco\Documents\GitHub\datazoom.amazonia/DESCRIPTION' (636ms)
-  preparing 'datazoom.amazonia': (2s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes (359ms)
E  creating vignettes (7m 59.9s)
   --- re-building 'COMEX.Rmd' using rmarkdown
   --- finished re-building 'COMEX.Rmd'
   
   --- re-building 'DEGRAD.Rmd' using rmarkdown
   tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2014_final_shp.zip'
   Content type 'application/zip' length 4324408 bytes (4.1 MB)
   ==================================================
   downloaded 4.1 MB
   
   tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2015_final_shp.zip'
   Content type 'application/zip' length 21966056 bytes (20.9 MB)
   ==================================================
   downloaded 20.9 MB
   
   tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2016_final_shp.zip'
   Content type 'application/zip' length 31212755 bytes (29.8 MB)
   ==================================================
   downloaded 29.8 MB
   
   tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2016_final_shp.zip'
   Content type 'application/zip' length 31212755 bytes (29.8 MB)
   ==================================================
   downloaded 29.8 MB
   
   --- finished re-building 'DEGRAD.Rmd'
   
   --- re-building 'DETER.Rmd' using rmarkdown
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100  312k    0  312k    0     0   948k      0 --:--:-- --:--:-- --:--:--  948k
   100 2767k    0 2767k    0     0  2082k      0 --:--:--  0:00:01 --:--:-- 2082k
   100 5295k    0 5295k    0     0  2273k      0 --:--:--  0:00:02 --:--:-- 2273k
   100 8242k    0 8242k    0     0  2476k      0 --:--:--  0:00:03 --:--:-- 2476k
   100 10.6M    0 10.6M    0     0  2510k      0 --:--:--  0:00:04 --:--:-- 2510k
   100 12.4M    0 12.4M    0     0  2394k      0 --:--:--  0:00:05 --:--:-- 2489k
   100 13.8M    0 13.8M    0     0  2242k      0 --:--:--  0:00:06 --:--:-- 2285k
   100 17.7M    0 17.7M    0     0  2483k      0 --:--:--  0:00:07 --:--:-- 2581k
   100 20.3M    0 20.3M    0     0  2419k      0 --:--:--  0:00:08 --:--:-- 2384k
   100 21.8M    0 21.8M    0     0  2397k      0 --:--:--  0:00:09 --:--:-- 2299k
   100 23.8M    0 23.8M    0     0  2339k      0 --:--:--  0:00:10 --:--:-- 2281k
   100 25.7M    0 25.7M    0     0  2323k      0 --:--:--  0:00:11 --:--:-- 2425k
   100 27.5M    0 27.5M    0     0  2286k      0 --:--:--  0:00:12 --:--:-- 1997k
   100 29.5M    0 29.5M    0     0  2272k      0 --:--:--  0:00:13 --:--:-- 2005k
   100 30.9M    0 30.9M    0     0  2214k      0 --:--:--  0:00:14 --:--:-- 1872k
   100 32.4M    0 32.4M    0     0  2169k      0 --:--:--  0:00:15 --:--:-- 1804k
   100 33.3M    0 33.3M    0     0  2090k      0 --:--:--  0:00:16 --:--:-- 1563k
   100 34.6M    0 34.6M    0     0  2046k      0 --:--:--  0:00:17 --:--:-- 1456k
   100 36.2M    0 36.2M    0     0  2023k      0 --:--:--  0:00:18 --:--:-- 1357k
   100 37.7M    0 37.7M    0     0  1999k      0 --:--:--  0:00:19 --:--:-- 1382k
   100 39.3M    0 39.3M    0     0  1979k      0 --:--:--  0:00:20 --:--:-- 1399k
   100 40.6M    0 40.6M    0     0  1953k      0 --:--:--  0:00:21 --:--:-- 1505k
   100 42.5M    0 42.5M    0     0  1950k      0 --:--:--  0:00:22 --:--:-- 1614k
   100 44.1M    0 44.1M    0     0  1936k      0 --:--:--  0:00:23 --:--:-- 1619k
   100 45.7M    0 45.7M    0     0  1925k      0 --:--:--  0:00:24 --:--:-- 1638k
   100 47.2M    0 47.2M    0     0  1910k      0 --:--:--  0:00:25 --:--:-- 1628k
   100 48.5M    0 48.5M    0     0  1887k      0 --:--:--  0:00:26 --:--:-- 1604k
   100 50.0M    0 50.0M    0     0  1874k      0 --:--:--  0:00:27 --:--:-- 1536k
   100 51.6M    0 51.6M    0     0  1865k      0 --:--:--  0:00:28 --:--:-- 1534k
   100 53.2M    0 53.2M    0     0  1859k      0 --:--:--  0:00:29 --:--:-- 1535k
   100 55.0M    0 55.0M    0     0  1859k      0 --:--:--  0:00:30 --:--:-- 1604k
   100 56.8M    0 56.8M    0     0  1857k      0 --:--:--  0:00:31 --:--:-- 1704k
   100 58.1M    0 58.1M    0     0  1841k      0 --:--:--  0:00:32 --:--:-- 1661k
   100 59.6M    0 59.6M    0     0  1832k      0 --:--:--  0:00:33 --:--:-- 1645k
   100 61.4M    0 61.4M    0     0  1833k      0 --:--:--  0:00:34 --:--:-- 1684k
   100 63.6M    0 63.6M    0     0  1845k      0 --:--:--  0:00:35 --:--:-- 1756k
   100 65.6M    0 65.6M    0     0  1850k      0 --:--:--  0:00:36 --:--:-- 1801k
   100 67.7M    0 67.7M    0     0  1857k      0 --:--:--  0:00:37 --:--:-- 1963k
   100 69.8M    0 69.8M    0     0  1866k      0 --:--:--  0:00:38 --:--:-- 2089k
   100 72.1M    0 72.1M    0     0  1878k      0 --:--:--  0:00:39 --:--:-- 2183k
   100 74.3M    0 74.3M    0     0  1888k      0 --:--:--  0:00:40 --:--:-- 2194k
   100 76.6M    0 76.6M    0     0  1898k      0 --:--:--  0:00:41 --:--:-- 2251k
   100 78.6M    0 78.6M    0     0  1902k      0 --:--:--  0:00:42 --:--:-- 2237k
   100 80.5M    0 80.5M    0     0  1903k      0 --:--:--  0:00:43 --:--:-- 2190k
   100 82.2M    0 82.2M    0     0  1899k      0 --:--:--  0:00:44 --:--:-- 2065k
   100 84.1M    0 84.1M    0     0  1900k      0 --:--:--  0:00:45 --:--:-- 1999k
   100 86.0M    0 86.0M    0     0  1901k      0 --:--:--  0:00:46 --:--:-- 1920k
   100 87.8M    0 87.8M    0     0  1900k      0 --:--:--  0:00:47 --:--:-- 1883k
   100 89.4M    0 89.4M    0     0  1894k      0 --:--:--  0:00:48 --:--:-- 1816k
   100 90.7M    0 90.7M    0     0  1883k      0 --:--:--  0:00:49 --:--:-- 1747k
   100 92.3M    0 92.3M    0     0  1878k      0 --:--:--  0:00:50 --:--:-- 1677k
   100 93.9M    0 93.9M    0     0  1875k      0 --:--:--  0:00:51 --:--:-- 1633k
   100 95.7M    0 95.7M    0     0  1873k      0 --:--:--  0:00:52 --:--:-- 1615k
   100 97.2M    0 97.2M    0     0  1868k      0 --:--:--  0:00:53 --:--:-- 1612k
   100 98.7M    0 98.7M    0     0  1861k      0 --:--:--  0:00:54 --:--:-- 1645k
   100 99.3M    0 99.3M    0     0  1859k      0 --:--:--  0:00:54 --:--:-- 1638k
   --- finished re-building 'DETER.Rmd'
   
   --- re-building 'GDP.Rmd' using rmarkdown
   --- finished re-building 'GDP.Rmd'
   
   --- re-building 'IPS.Rmd' using rmarkdown
   tentando a URL 'http://www.ipsamazonia.org.br/assets/IPS_Tabela_Completa-8bb3b841e46c8fb17b0331d8ea92bef3.xlsx'
   Quitting from lines 31-33 (IPS.Rmd) 
   Error: processing vignette 'IPS.Rmd' failed with diagnostics:
   não foi possível abrir a URL 'http://www.ipsamazonia.org.br/assets/IPS_Tabela_Completa-8bb3b841e46c8fb17b0331d8ea92bef3.xlsx'
   --- failed re-building 'IPS.Rmd'
   
   --- re-building 'MAPBIOMAS.Rmd' [...]

2021-02-22 23:30 UTC, arthurcbps commented
> @arthurcbps, o `devtools::check` falhou. Aparentemente é um erro do vignette do IPS.Rmd. Colo abaixo o resultado no console.
> 
> Uma dúvida: vi que você alterou em todos os vignettes o comando `{r, include = FALSE}` para `{r setup, include = FALSE}`. Você está ativando os vignettes com esse comando? Não me parece isso. Lembrando que o que eu pedi foi ativar os vignettes e nos exemplos colocar o `\dontrun{}`. Assim como você fez **prodes.R**
> 
> ```
> > devtools::check()
> Updating datazoom.amazonia documentation
> Loading datazoom.amazonia
> Writing NAMESPACE
> Writing NAMESPACE
> -- Building --------------------------------------------------- datazoom.amazonia --
> Setting env vars:
> * CFLAGS    : -Wall -pedantic
> * CXXFLAGS  : -Wall -pedantic
> * CXX11FLAGS: -Wall -pedantic
> ------------------------------------------------------------------------------------
> WARNING: Rtools is required to build R packages, but is not currently installed.
> 
> Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
> √  checking for file 'C:\Users\Francisco\Documents\GitHub\datazoom.amazonia/DESCRIPTION' (636ms)
> -  preparing 'datazoom.amazonia': (2s)
> √  checking DESCRIPTION meta-information ... 
> -  installing the package to build vignettes (359ms)
> E  creating vignettes (7m 59.9s)
>    --- re-building 'COMEX.Rmd' using rmarkdown
>    --- finished re-building 'COMEX.Rmd'
>    
>    --- re-building 'DEGRAD.Rmd' using rmarkdown
>    tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2014_final_shp.zip'
>    Content type 'application/zip' length 4324408 bytes (4.1 MB)
>    ==================================================
>    downloaded 4.1 MB
>    
>    tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2015_final_shp.zip'
>    Content type 'application/zip' length 21966056 bytes (20.9 MB)
>    ==================================================
>    downloaded 20.9 MB
>    
>    tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2016_final_shp.zip'
>    Content type 'application/zip' length 31212755 bytes (29.8 MB)
>    ==================================================
>    downloaded 29.8 MB
>    
>    tentando a URL 'http://www.obt.inpe.br/OBT/assuntos/programas/amazonia/degrad/arquivos/degrad2016_final_shp.zip'
>    Content type 'application/zip' length 31212755 bytes (29.8 MB)
>    ==================================================
>    downloaded 29.8 MB
>    
>    --- finished re-building 'DEGRAD.Rmd'
>    
>    --- re-building 'DETER.Rmd' using rmarkdown
>      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                     Dload  Upload   Total   Spent    Left  Speed
>    
>      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>    100  312k    0  312k    0     0   948k      0 --:--:-- --:--:-- --:--:--  948k
>    100 2767k    0 2767k    0     0  2082k      0 --:--:--  0:00:01 --:--:-- 2082k
>    100 5295k    0 5295k    0     0  2273k      0 --:--:--  0:00:02 --:--:-- 2273k
>    100 8242k    0 8242k    0     0  2476k      0 --:--:--  0:00:03 --:--:-- 2476k
>    100 10.6M    0 10.6M    0     0  2510k      0 --:--:--  0:00:04 --:--:-- 2510k
>    100 12.4M    0 12.4M    0     0  2394k      0 --:--:--  0:00:05 --:--:-- 2489k
>    100 13.8M    0 13.8M    0     0  2242k      0 --:--:--  0:00:06 --:--:-- 2285k
>    100 17.7M    0 17.7M    0     0  2483k      0 --:--:--  0:00:07 --:--:-- 2581k
>    100 20.3M    0 20.3M    0     0  2419k      0 --:--:--  0:00:08 --:--:-- 2384k
>    100 21.8M    0 21.8M    0     0  2397k      0 --:--:--  0:00:09 --:--:-- 2299k
>    100 23.8M    0 23.8M    0     0  2339k      0 --:--:--  0:00:10 --:--:-- 2281k
>    100 25.7M    0 25.7M    0     0  2323k      0 --:--:--  0:00:11 --:--:-- 2425k
>    100 27.5M    0 27.5M    0     0  2286k      0 --:--:--  0:00:12 --:--:-- 1997k
>    100 29.5M    0 29.5M    0     0  2272k      0 --:--:--  0:00:13 --:--:-- 2005k
>    100 30.9M    0 30.9M    0     0  2214k      0 --:--:--  0:00:14 --:--:-- 1872k
>    100 32.4M    0 32.4M    0     0  2169k      0 --:--:--  0:00:15 --:--:-- 1804k
>    100 33.3M    0 33.3M    0     0  2090k      0 --:--:--  0:00:16 --:--:-- 1563k
>    100 34.6M    0 34.6M    0     0  2046k      0 --:--:--  0:00:17 --:--:-- 1456k
>    100 36.2M    0 36.2M    0     0  2023k      0 --:--:--  0:00:18 --:--:-- 1357k
>    100 37.7M    0 37.7M    0     0  1999k      0 --:--:--  0:00:19 --:--:-- 1382k
>    100 39.3M    0 39.3M    0     0  1979k      0 --:--:--  0:00:20 --:--:-- 1399k
>    100 40.6M    0 40.6M    0     0  1953k      0 --:--:--  0:00:21 --:--:-- 1505k
>    100 42.5M    0 42.5M    0     0  1950k      0 --:--:--  0:00:22 --:--:-- 1614k
>    100 44.1M    0 44.1M    0     0  1936k      0 --:--:--  0:00:23 --:--:-- 1619k
>    100 45.7M    0 45.7M    0     0  1925k      0 --:--:--  0:00:24 --:--:-- 1638k
>    100 47.2M    0 47.2M    0     0  1910k      0 --:--:--  0:00:25 --:--:-- 1628k
>    100 48.5M    0 48.5M    0     0  1887k      0 --:--:--  0:00:26 --:--:-- 1604k
>    100 50.0M    0 50.0M    0     0  1874k      0 --:--:--  0:00:27 --:--:-- 1536k
>    100 51.6M    0 51.6M    0     0  1865k      0 --:--:--  0:00:28 --:--:-- 1534k
>    100 53.2M    0 53.2M    0     0  1859k      0 --:--:--  0:00:29 --:--:-- 1535k
>    100 55.0M    0 55.0M    0     0  1859k      0 --:--:--  0:00:30 --:--:-- 1604k
>    100 56.8M    0 56.8M    0     0  1857k      0 --:--:--  0:00:31 --:--:-- 1704k
>    100 58.1M    0 58.1M    0     0  1841k      0 --:--:--  0:00:32 --:--:-- 1661k
>    100 59.6M    0 59.6M    0     0  1832k      0 --:--:--  0:00:33 --:--:-- 1645k
>    100 61.4M    0 61.4M    0     0  1833k      0 --:--:--  0:00:34 --:--:-- 1684k
>    100 63.6M    0 63.6M    0     0  1845k      0 --:--:--  0:00:35 --:--:-- 1756k
>    100 65.6M    0 65.6M    0     0  1850k      0 --:--:--  0:00:36 --:--:-- 1801k
>    100 67.7M    0 67.7M    0     0  1857k      0 --:--:--  0:00:37 --:--:-- 1963k
>    100 69.8M    0 69.8M    0     0  1866k      0 --:--:--  0:00:38 --:--:-- 2089k
>    100 72.1M    0 72.1M    0     0  1878k      0 --:--:--  0:00:39 --:--:-- 2183k
>    100 74.3M    0 74.3M    0     0  1888k      0 --:--:--  0:00:40 --:--:-- 2194k
>    100 76.6M    0 76.6M    0     0  1898k      0 --:--:--  0:00:41 --:--:-- 2251k
>    100 78.6M    0 78.6M    0     0  1902k      0 --:--:--  0:00:42 --:--:-- 2237k
>    100 80.5M    0 80.5M    0     0  1903k      0 --:--:--  0:00:43 --:--:-- 2190k
>    100 82.2M    0 82.2M    0     0  1899k      0 --:--:--  0:00:44 --:--:-- 2065k
>    100 84.1M    0 84.1M    0     0  1900k      0 --:--:--  0:00:45 --:--:-- 1999k
>    100 86.0M    0 86.0M    0     0  1901k      0 --:--:--  0:00:46 --:--:-- 1920k
>    100 87.8M    0 87.8M    0     0  1900k      0 --:--:--  0:00:47 --:--:-- 1883k
>    100 89.4M    0 89.4M    0     0  1894k      0 --:--:--  0:00:48 --:--:-- 1816k
>    100 90.7M    0 90.7M    0     0  1883k      0 --:--:--  0:00:49 --:--:-- 1747k
>    100 92.3M    0 92.3M    0     0  1878k      0 --:--:--  0:00:50 --:--:-- 1677k
>    100 93.9M    0 93.9M    0     0  1875k      0 --:--:--  0:00:51 --:--:-- 1633k
>    100 95.7M    0 95.7M    0     0  1873k      0 --:--:--  0:00:52 --:--:-- 1615k
>    100 97.2M    0 97.2M    0     0  1868k      0 --:--:--  0:00:53 --:--:-- 1612k
>    100 98.7M    0 98.7M    0     0  1861k      0 --:--:--  0:00:54 --:--:-- 1645k
>    100 99.3M    0 99.3M    0     0  1859k      0 --:--:--  0:00:54 --:--:-- 1638k
>    --- finished re-building 'DETER.Rmd'
>    
>    --- re-building 'GDP.Rmd' using rmarkdown
>    --- finished re-building 'GDP.Rmd'
>    
>    --- re-building 'IPS.Rmd' using rmarkdown
>    tentando a URL 'http://www.ipsamazonia.org.br/assets/IPS_Tabela_Completa-8bb3b841e46c8fb17b0331d8ea92bef3.xlsx'
>    Quitting from lines 31-33 (IPS.Rmd) 
>    Error: processing  [...]

2021-03-10 19:50 UTC, FranciscoCavalcanti approved these changes

2021-03-10 19:50 UTC, merged