Sigmine
datazoompuc/datazoom.amazonia pull request #23
Opened 2021-02-12 00:13 UTC by BrunoAlcantaraD

Criei o pull request só para facilitar os comentários do código. Ainda falta atualizar o readme e a versão do pacote.

2021-02-18 13:33 UTC, FranciscoCavalcanti requested changes
@BrunoAlcantaraD rodei o `devtools::check()` e deu tudo certo. Também rodei o comando descrito na vignette **SIGMINE.Rmd** e consegui baixar os dados.

Por outro lado, senti falta de uma documentação básica para entender o que as variáveis desses dados estão informando.

Também é preciso atualizar as versões no **NEW.md** e **DESCRIPTION**, além de atualizar o **README.md**.

Uma dúvida, é possível transformar essa base de dados de tal forma que faça sentido ao nível município x ano?

2021-02-18 13:33 UTC, FranciscoCavalcanti commented on R/sigmine.R
> +#' @description Download and filter data on type of soil covering by year
Essa não é a descrição dessa função. É preciso reescrever.

2021-02-18 13:33 UTC, FranciscoCavalcanti commented on R/sigmine.R
> +    operation_crs <- sf::st_crs("+proj=poly +lat_0=0 +lon_0=-54 +x_0=5000000 +y_0=10000000 +ellps=aust_SA +units=m +no_defs")
Adicionar aqui algum comentário racionalizando porque a escolha desse CRS específico.

2021-02-18 13:33 UTC, FranciscoCavalcanti commented on R/sigmine.R
> +    ret <- a
Dois comentários sobre o nome das variáveis:

1. Da uma olhada no nome usado das variáveis de outras funções do pacote `datazoom.amazonia`, e tenta usar o nome padronizado.
2. Algumas variáveis não possuem qualquer descrição e isso implica em um custo de entendimento dos dados por parte do usuario. Por exemplo, eu como usuário ignorante sobre o tema, não faço ideia do que significa **id**, **processo**, **area_ha**. Talvez uma solução seria explicar isso na descrição da função ou no vignettes.

2021-02-18 13:33 UTC, FranciscoCavalcanti commented on R/sigmine.R
> +#' load_sigmine(space_aggregation = 'municipality', source = NULL)
Vamos mudar a conveção sobre os exemplos para que diminuia problemas com os Checks do Github Action. Então é seguinte:

Sempre colocar os examplos entre` \dontrun{}.` Ou seja:
```
\dontrun{
load_sigmine(space_aggregation = 'municipality', source = NULL)
}


```

2021-02-18 22:38 UTC, BrunoAlcantaraD commented on R/sigmine.R
> +#' @description Download and filter data on type of soil covering by year
Mudei

2021-02-18 22:40 UTC, BrunoAlcantaraD commented on R/sigmine.R
> +    operation_crs <- sf::st_crs("+proj=poly +lat_0=0 +lon_0=-54 +x_0=5000000 +y_0=10000000 +ellps=aust_SA +units=m +no_defs")
Eu usei esse porque foi o usado no código do Victor. Qual comentário você gostaria que eu colocasse?

2021-02-18 22:50 UTC, BrunoAlcantaraD commented on R/sigmine.R
> +    ret <- a
id e processo são uns números e letras. É uma coisa técnica do ministério de minas e energia que, para mim não serve para nada. Contudo, como a base de dados vinha com essas informações, decidi não tirar, principalmente para quem quer a base idêntica à disponível no site do sigmine. area_ha eu já tinha renomeado para area_hectares e as outras informações acho que estão bem compreensíveis. Qualquer coisa, se você achar que algo não está claro nos nomes coloca aí em baixo.

2021-02-18 22:52 UTC, BrunoAlcantaraD commented on R/sigmine.R
> +#' load_sigmine(space_aggregation = 'municipality', source = NULL)
Feito

2021-02-18 22:56 UTC, BrunoAlcantaraD commented
> @BrunoAlcantaraD rodei o `devtools::check()` e deu tudo certo. Também rodei o comando descrito na vignette **SIGMINE.Rmd** e consegui baixar os dados.
> 
> Por outro lado, senti falta de uma documentação básica para entender o que as variáveis desses dados estão informando.
> 
> Também é preciso atualizar as versões no **NEW.md** e **DESCRIPTION**, além de atualizar o **README.md**.
> 
> Uma dúvida, é possível transformar essa base de dados de tal forma que faça sentido ao nível município x ano?

É possível, sim, é só fazer um aggregate(FUN=sum), deletando as colunas sem ser município e área.

2021-02-26 15:12 UTC, FranciscoCavalcanti approved these changes
@BrunoAlcantaraD, eu vou aceitar o seu Pull Request. O código passou no checks e consegui baixar os dados com o comando `load_sigmine`. Porém eu identifiquei algumas possíveis incongruências e a falta do dicionário em inglês.

Especificamente, me chamou atenção que na Linha 48 do arquivo **R/sigmine.R**:
`
names(a)[names(a) == 'AREA_HA'] <- 'area_hectares'
`
Enquanto que na linha Linha 83:

`names(al)[names(al) == 'calculated_area'] <- 'area_calculada_m2'
`
É preciso que os dados tenham um padrão claro: hectares ou metro ao quadrado?

Essas pequenas correções podem ser feitas em uma outra branch, criada a partir da branch `master` que vou mergear com esse Pull Request..

2021-02-26 18:51 UTC, merged