Produção Pecuária Municipal
datazoompuc/datazoom.amazonia pull request #27
Opened 2021-03-09 01:26 UTC by dacbarbosa

2021-03-09 09:12 UTC, dacbarbosa commented
Conforme discutido no Slack, o PR falhou devido a presence de caracteres ASCIII, os quais não são bem lidados com o R ao fazermos portabilidade entre diferentes áreas com diferentes encodings... Vou corrigir esse problema e fazer um novo PR.
![image](https://user-images.githubusercontent.com/29846465/110446903-6d304480-809e-11eb-87bc-39aabfcb9ea9.png)

2021-03-09 12:39 UTC, dacbarbosa commented
Non-Ascii ajustados

2021-03-10 09:18 UTC, dacbarbosa commented
@FranciscoCavalcanti o "erro" foi na compilação das Vignettes mesmo. Minha sugestão é aceitar o pull request na forma atual e eu vou tentar tornar nossa testagem dos códigos dentro das vignettes e/ou examples mais robust nos próximos dias.

2021-03-15 23:22 UTC, FranciscoCavalcanti requested changes
@dacbarbosa muito bom trabalho.

Ainda não terminei toda a revisão do código, muito em função de problemas nos testes do Github Action, no qual alguns sites cairam (mas não tem relação com a PPM).

No entanto, apenas para adiantar, eu gostaria que você fizesse algumas pequenas alterações faltantes.

1. Criar o viggette para a PPM. Para o codigo nao ficar muito pesado na hora de rodar os testes, voce poderia colocar \dontrun{} nos exemplos.
2. Atualizar o arquivo NEWS.md
3. Atualizar o arquivo DESCRIPTION com um novo numero de versão e introduzir o seu nome como um dos autores do codigo
4. Atualizar o arquivo README.

Vai fazendo isso, enquanto continuo testando o codigo e torcendo para o Github Action passar novamente.

2021-03-23 13:06 UTC, closed without merging