Tweaks and Upgrades
datazoompuc/datazoom.amazonia pull request #7
Opened 2020-12-14 20:42 UTC by victordamatta

Algumas mudanças organizacionais, mais documentação e a implementação de dados para população e pib per capita.

2020-12-28 17:45 UTC, FranciscoCavalcanti requested changes
Houve um warning com o arquivo **municipios.R** com relação ao nome **Munic\u00edpio**. Este warning está aparecendo tanto rodando `devtools::check()` quanto no **Github Action**.

Especificamente:

```
> checking R files for syntax errors ... WARNING
  Warning in file 'R/municipios.R':
    unable to translate 'Munic<U+00ED>pio' to native encoding

```

Vou marcar **Request changes** devido a este pequeno problema.

2021-01-05 23:33 UTC, FranciscoCavalcanti approved these changes
Passou bem `devtools::check()` e em todos os 5 checks do **Github Action**.

Approved.

2021-01-05 23:33 UTC, FranciscoCavalcanti commented on R/municipios.R
> +    "Municipio" = "Municipality",
Solução não perfeita, but who cares? Por mim tá tranquilo

2021-01-05 23:34 UTC, merged

2021-01-06 02:33 UTC, victordamatta commented on R/municipios.R
> +    "Municipio" = "Municipality",
😬